/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hashcode;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Akshay L Aradhya
 * https://github.com/DollarAkshay/Hexagonal-Lock-Screen
 * 
 */
public class Lock_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Lock_Screen
     */
    public Lock_Screen() {
        
        initComponents();
        
        Calendar cal = Calendar.getInstance();
    	cal.getTime();
    	SimpleDateFormat sdf = new SimpleDateFormat("hh:mm");
        Time_Display.setText(sdf.format(cal.getTime()));
        Pattern_Set.doClick();
        dp.setSize(450, 750);
        dp.setBackground(Color.black);
        Screen.add(dp,0);
    }
    
    public boolean isInsideHexagon(float x0, float y0, float d, float x, float y) {
        
        float dx = Math.abs(x - x0)/d;
        float dy = Math.abs(y - y0)/d;
        float a = (float) (0.25 * Math.sqrt(3.0));
        return (dy <= a) && (a*dx + 0.25*dy <= 0.5*a);
        
    }
    
    int getHexAt(int x,int y){
        
        for (int i = 0; i < dp.n_hex; i++) {
            if(isInsideHexagon(x,y,dp.hex_side*2,dp.hex_x[i],dp.hex_y[i]))
                return i;
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Screen = new javax.swing.JPanel();
        Screen_Off = new javax.swing.JLabel();
        Time_Display = new javax.swing.JLabel();
        Notif = new javax.swing.JLabel();
        Wallpaper = new javax.swing.JLabel();
        Lock_Button = new javax.swing.JButton();
        Pattern_Set = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Debug = new javax.swing.JTextArea();
        Sub_head_1 = new javax.swing.JLabel();
        Level_Slider = new javax.swing.JSlider();
        Sub_head_2 = new javax.swing.JLabel();
        Length_Slider = new javax.swing.JSlider();
        Red = new javax.swing.JLabel();
        Yellow = new javax.swing.JLabel();
        Orange = new javax.swing.JLabel();
        Border_Toggle = new javax.swing.JToggleButton();
        Blue = new javax.swing.JLabel();
        Green = new javax.swing.JLabel();
        Pink = new javax.swing.JLabel();
        Sub_head_4 = new javax.swing.JLabel();
        Sub_head_3 = new javax.swing.JLabel();
        Exit_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Screen.setBackground(new java.awt.Color(0, 0, 0));
        Screen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Screen.setOpaque(false);
        Screen.setPreferredSize(new java.awt.Dimension(450, 750));
        Screen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ScreenMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ScreenMouseMoved(evt);
            }
        });
        Screen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ScreenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ScreenMouseReleased(evt);
            }
        });
        Screen.setLayout(null);

        Screen_Off.setBackground(new java.awt.Color(0, 0, 0));
        Screen_Off.setOpaque(true);
        Screen_Off.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Screen_OffMouseReleased(evt);
            }
        });
        Screen.add(Screen_Off);
        Screen_Off.setBounds(0, 0, 450, 0);

        Time_Display.setForeground(new java.awt.Color(255, 255, 255));
        Time_Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time_Display.setText("12:00");
        Screen.add(Time_Display);
        Time_Display.setBounds(401, 0, 50, 20);

        Notif.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Notif.setToolTipText("");
        Screen.add(Notif);
        Notif.setBounds(0, 0, 0, 20);

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yellow_Wallpaper_1.png"))); // NOI18N
        Screen.add(Wallpaper);
        Wallpaper.setBounds(0, 0, 450, 750);

        getContentPane().add(Screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 32, -1, -1));

        Lock_Button.setBackground(new java.awt.Color(0, 102, 255));
        Lock_Button.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        Lock_Button.setText("LOCK");
        Lock_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lock_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Lock_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 155, 68));

        Pattern_Set.setBackground(new java.awt.Color(0, 102, 255));
        Pattern_Set.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        Pattern_Set.setSelected(true);
        Pattern_Set.setText("Set Pattern");
        Pattern_Set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pattern_SetActionPerformed(evt);
            }
        });
        getContentPane().add(Pattern_Set, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 184, 64));

        Debug.setColumns(20);
        Debug.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Debug.setRows(5);
        jScrollPane1.setViewportView(Debug);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 870, 450, 160));

        Sub_head_1.setFont(new java.awt.Font("Prestige Elite Std", 0, 24)); // NOI18N
        Sub_head_1.setText("Choose Theme :");
        getContentPane().add(Sub_head_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 220, 40));

        Level_Slider.setMajorTickSpacing(1);
        Level_Slider.setMaximum(7);
        Level_Slider.setMinimum(1);
        Level_Slider.setPaintLabels(true);
        Level_Slider.setPaintTicks(true);
        Level_Slider.setSnapToTicks(true);
        Level_Slider.setValue(4);
        Level_Slider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Level_SliderMouseReleased(evt);
            }
        });
        getContentPane().add(Level_Slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 470, 61));

        Sub_head_2.setFont(new java.awt.Font("Prestige Elite Std", 0, 24)); // NOI18N
        Sub_head_2.setText("Hexagon Length :");
        getContentPane().add(Sub_head_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, 270, 40));

        Length_Slider.setMajorTickSpacing(10);
        Length_Slider.setMaximum(50);
        Length_Slider.setMinimum(10);
        Length_Slider.setMinorTickSpacing(5);
        Length_Slider.setPaintLabels(true);
        Length_Slider.setPaintTicks(true);
        Length_Slider.setSnapToTicks(true);
        Length_Slider.setToolTipText("");
        Length_Slider.setValue(40);
        Length_Slider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Length_SliderMouseReleased(evt);
            }
        });
        getContentPane().add(Length_Slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 520, 470, 61));

        Red.setBackground(new java.awt.Color(255, 0, 0));
        Red.setForeground(new java.awt.Color(0, 51, 255));
        Red.setOpaque(true);
        Red.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RedMouseClicked(evt);
            }
        });
        getContentPane().add(Red, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 70, 70));

        Yellow.setBackground(new java.awt.Color(255, 190, 0));
        Yellow.setForeground(new java.awt.Color(0, 51, 255));
        Yellow.setOpaque(true);
        Yellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YellowMouseClicked(evt);
            }
        });
        getContentPane().add(Yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 70, 70));

        Orange.setBackground(new java.awt.Color(255, 102, 0));
        Orange.setForeground(new java.awt.Color(0, 51, 255));
        Orange.setOpaque(true);
        Orange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrangeMouseClicked(evt);
            }
        });
        getContentPane().add(Orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 100, 70, 70));

        Border_Toggle.setBackground(new java.awt.Color(0, 102, 255));
        Border_Toggle.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        Border_Toggle.setText("Borderless");
        Border_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Border_ToggleActionPerformed(evt);
            }
        });
        getContentPane().add(Border_Toggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 184, 64));

        Blue.setBackground(new java.awt.Color(0, 153, 204));
        Blue.setForeground(new java.awt.Color(0, 51, 255));
        Blue.setOpaque(true);
        Blue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlueMouseClicked(evt);
            }
        });
        getContentPane().add(Blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, 70, 70));

        Green.setBackground(new java.awt.Color(0, 204, 0));
        Green.setForeground(new java.awt.Color(0, 51, 255));
        Green.setOpaque(true);
        Green.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GreenMouseClicked(evt);
            }
        });
        getContentPane().add(Green, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 170, 70, 70));

        Pink.setBackground(new java.awt.Color(255, 0, 204));
        Pink.setForeground(new java.awt.Color(0, 51, 255));
        Pink.setOpaque(true);
        Pink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PinkMouseClicked(evt);
            }
        });
        getContentPane().add(Pink, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 170, 70, 70));

        Sub_head_4.setFont(new java.awt.Font("Prestige Elite Std", 0, 24)); // NOI18N
        Sub_head_4.setText("Debug info :");
        getContentPane().add(Sub_head_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 830, 220, 40));

        Sub_head_3.setFont(new java.awt.Font("Prestige Elite Std", 0, 24)); // NOI18N
        Sub_head_3.setText("No. of Levels :");
        getContentPane().add(Sub_head_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, 220, 40));

        Exit_Button.setBackground(new java.awt.Color(243, 0, 0));
        Exit_Button.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        Exit_Button.setForeground(new java.awt.Color(255, 255, 255));
        Exit_Button.setText("X");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 0, 60, 60));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 150)); // NOI18N
        jLabel1.setText("TRY ME !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 710, -1, -1));

        Background.setBackground(new java.awt.Color(0, 51, 102));
        Background.setOpaque(true);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private DrawPattern dp = new DrawPattern();
    int prev_dot;
    int check_pattern[] = new int[1000];
    int set_pattern[] = new int[1000];
    int check_dots=0,set_dots=0;
    
    
    private void ScreenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScreenMouseMoved
    
    }//GEN-LAST:event_ScreenMouseMoved

    private void ScreenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScreenMouseDragged
    if(dp.size().height>0){
        int h = getHexAt(evt.getX(),evt.getY());
        if(prev_dot!=h && h!=-1 && dp.hex_selected[h]!=true){
            if(Pattern_Set.isSelected())
                set_pattern[set_dots++]=h;
            else
                check_pattern[check_dots++]=h;
            prev_dot=h;
            dp.hex_selected[h]=true;
        }
        repaint();
    }
    }//GEN-LAST:event_ScreenMouseDragged

    @SuppressWarnings("empty-statement")
    private void ScreenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScreenMouseReleased
if(dp.size().height>0){
        
        if(Pattern_Set.isSelected()==true){
            Debug.setText("Pattern is Set ");
            for (int i = 0; i < set_dots; i++) {
                Debug.append(set_pattern[i]+",");
            }
            JOptionPane.showMessageDialog(null,"Your Pattern has been set.");
            Pattern_Set.doClick();
        }
        else{
            dp.check=true;
            
            boolean correct = true;
            if(set_dots==check_dots){
                for (int i = 0; i < check_dots; i++) {
                    if(set_pattern[i]!=check_pattern[i]){
                        correct=false;
                        break;
                    }   
                }
            }
            else
                correct = false;
            
            if(correct){
                
                dp.setSize(0,0);
            }
            else{
                JOptionPane.showMessageDialog(null,"Your Pattern is Incorrect");
            }
        }
        
        
        
        for (int i = 0; i < dp.n_hex; i++) {
            dp.hex_selected[i]=false;
        }
        repaint();
}
    }//GEN-LAST:event_ScreenMouseReleased

    private void ScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScreenMousePressed

        if(dp.size().height>0){
        int h = getHexAt(evt.getX(),evt.getY());
        if(h!=-1){
            dp.hex_selected[h]=true;
            if(Pattern_Set.isSelected()){
                int i=100;
                while(--i>=0) set_pattern[i]=-1;
                dp.check=false;
                set_dots=0;
                set_pattern[set_dots++]=h;
            }
            else{
                dp.check=true;
                check_dots=0;
                check_pattern[check_dots++]=h;
            }
            prev_dot=h;
        }
        repaint();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_ScreenMousePressed

    private void Pattern_SetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pattern_SetActionPerformed
        if(dp.size().height>0){
            if(Pattern_Set.isSelected()){
                Pattern_Set.setBackground(new Color(0,220,20));
                Pattern_Set.setText("Done");
            }
            else{
            
                Pattern_Set.setBackground(new Color(0,102,255));
                Pattern_Set.setText("Set Pattern");
            }
        }
        
    }//GEN-LAST:event_Pattern_SetActionPerformed

    private void Lock_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lock_ButtonActionPerformed
        
        Screen_Off.setSize(450,750);
        
    }//GEN-LAST:event_Lock_ButtonActionPerformed

    private void Level_SliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Level_SliderMouseReleased
    dp.levels = Level_Slider.getValue();
    repaint();

    }//GEN-LAST:event_Level_SliderMouseReleased

    private void Length_SliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Length_SliderMouseReleased
      dp.hex_side = Length_Slider.getValue();
      repaint();

    }//GEN-LAST:event_Length_SliderMouseReleased

    private void RedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RedMouseClicked

        dp.theme = new Color(255,30,30);
        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_wallpaper_1.png")));

    }//GEN-LAST:event_RedMouseClicked

    private void YellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YellowMouseClicked
     
        dp.theme = new Color(255,204,0);
        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yellow_wallpaper_1.png")));

    }//GEN-LAST:event_YellowMouseClicked

    private void OrangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrangeMouseClicked
     
        dp.theme = new Color(255,102,0);
        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Orange_wallpaper_1.png")));
        
    }//GEN-LAST:event_OrangeMouseClicked

    private void BlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlueMouseClicked

        dp.theme = new Color(0,153,204);
        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Blue_wallpaper_1.png")));

    }//GEN-LAST:event_BlueMouseClicked

    private void GreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreenMouseClicked
        
        dp.theme = new Color(0,204,0);
        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Green_wallpaper_1.png")));
        
    }//GEN-LAST:event_GreenMouseClicked

    private void PinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PinkMouseClicked

        dp.theme = new Color(255,0,204);
        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pink_wallpaper_1.png")));

    }//GEN-LAST:event_PinkMouseClicked

    private void Screen_OffMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Screen_OffMouseReleased

        Screen_Off.setSize(0,0);
        dp.setSize(450,750);
        
    }//GEN-LAST:event_Screen_OffMouseReleased

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed

       dispose();
       System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void Border_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Border_ToggleActionPerformed
        
        if(Border_Toggle.isSelected()){
            Border_Toggle.setBackground(new Color(0,220,20));
            Border_Toggle.setText("Border");
            dp.border=false;
        }
        else{
            Border_Toggle.setBackground(new Color(0,102,255));
            Border_Toggle.setText("Borderless");
            dp.border=true;
        }
        repaint();
        
    }//GEN-LAST:event_Border_ToggleActionPerformed
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lock_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lock_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lock_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lock_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lock_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Blue;
    private javax.swing.JToggleButton Border_Toggle;
    private javax.swing.JTextArea Debug;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel Green;
    private javax.swing.JSlider Length_Slider;
    private javax.swing.JSlider Level_Slider;
    private javax.swing.JButton Lock_Button;
    private javax.swing.JLabel Notif;
    private javax.swing.JLabel Orange;
    private javax.swing.JToggleButton Pattern_Set;
    private javax.swing.JLabel Pink;
    private javax.swing.JLabel Red;
    private javax.swing.JPanel Screen;
    private javax.swing.JLabel Screen_Off;
    private javax.swing.JLabel Sub_head_1;
    private javax.swing.JLabel Sub_head_2;
    private javax.swing.JLabel Sub_head_3;
    private javax.swing.JLabel Sub_head_4;
    private javax.swing.JLabel Time_Display;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JLabel Yellow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
